# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab5661eaabaa5d384ed7f20fbb290da4392df889238b206ba3b9270867e6a94e4f9519d02fbaea61a29094f7942d848895095538809da7c285b15a717101724f

test:
  secret_key_base: 15a86a9df9a77a688b87b0d8da07ace5fac20299368fee48fd74fdc3f198daf522e73ad9edee37c82bc0e7d5a7d62d849026832a85e9d337d4bf11382ac7ff73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
